### ISSUE TITLE
Table Covers

### ISSUE THREAD

**Issue by ophilli** [clemsonMakerspace/admin#21]
[Clear](https://www.amazon.com/dp/B0009EQ9DY)
[Opaque White](https://www.amazon.com/dp/B000KKIQ3S)

**Comment by ophilli** [comment]
Cole - you mentioned you would look for some sticky sheets. Assigning this to you.

**Comment by coledemarco** [comment]
60in x 16ft = All the vinyl we'll ever need......$120 http://carwrapsupplier.com/product/economy-matte-orange/

**Comment by coledemarco** [comment]
As said by Dr Todd and Tim Howard, this task has been placed on hold. the cost does not out way the benefits. We should pursue this option when the tables are not aesthetically pleasing
