### ISSUE TITLE
Pricing on Injection Molding

### ISSUE THREAD

**Issue by ophilli** [clemsonMakerspace/admin#39]
Please call around and figure out some price ranges for appropriate injection molding machines. Please request to have copies of the quotes emailed to makerspace@clemson.edu.

http://www.morganindustriesinc.com/

**Comment by coledemarco** [comment]
5%  Educational Discount off all product (Spoke with Chuck Land)
-Will be provided with formal quote
-Ships from Cali
-Ballpark # for G100T (Most popular for Universities) Approx $24k - 5% discount

**Comment by ophilli** [comment]
@coledemarco Please post full pricing sheet once you receive it - I would love to see it.

I'm closing this in the meantime, as we are no longer pursuing IM equipment.
