### ISSUE TITLE
Byrnes RA Makerspace Event

### ISSUE THREAD

**Issue by ophilli** [clemsonMakerspace/admin#46]

**Comment by coledemarco** [comment]
If needed for a bigger room, talk to Mr Howard

**Comment by coledemarco** [comment]
Scheduled! March 31st 4:30

**Comment by ophilli** [comment]
Get room approved w/ Brittany

**Comment by coledemarco** [comment]
Room Approved and Booked. Check. Ready to go

**Comment by ophilli** [comment]
How'd this go?

**Comment by coledemarco** [comment]
went well, about 10 people showed up and we had a good training session
