### ISSUE TITLE
Add Room 333 to new MOU

### ISSUE THREAD

**Issue by coledemarco** [clemsonMakerspace/admin#59]

**Comment by coledemarco** [comment]
was this complete and added to the new MOU? @ophilli At least an understanding that we use that room a lot

**Comment by ophilli** [comment]
This was discussed at our meeting.

Dr. Marek was extremely impressed that we utilized 333, he was not aware of
the extent of our utilization of the Watt Center's technology.

I will leave this issue open until I complete the draft of the MOU
addendums.
